import type { Transaction } from "./finance";

export const profile = {
  name: "Uan Samudera",
  summary:
    "35 years old, married with one 4-year-old child. His wife is 5 months pregnant with their second child.",
};

export const transactions: Transaction[] = [
  {
    id: "t1",
    title: "Gaji Bulanan - PT Nusantara Karya",
    amount: 18_500_000,
    type: "income",
    category: "Salary",
    date: "2026-09-01",
  },
  {
    id: "t2",
    title: "Dividen Reksadana Saham",
    amount: 750_000,
    type: "income",
    category: "Investment",
    date: "2026-09-05",
  },
  {
    id: "t3",
    title: "Belanja Bulanan - Superindo",
    amount: 1_850_000,
    type: "expense",
    category: "Food",
    date: "2026-09-02",
  },
  {
    id: "t4",
    title: "Makan Siang & Jajan Keluarga",
    amount: 1_450_000,
    type: "expense",
    category: "Food",
    date: "2026-09-08",
  },
  {
    id: "t5",
    title: "Warung & Katering Mingguan",
    amount: 900_000,
    type: "expense",
    category: "Food",
    date: "2026-09-11",
  },
  {
    id: "t6",
    title: "Isi Bensin Pertamina",
    amount: 650_000,
    type: "expense",
    category: "Transport",
    date: "2026-09-03",
  },
  {
    id: "t7",
    title: "Servis Motor Bulanan",
    amount: 300_000,
    type: "expense",
    category: "Transport",
    date: "2026-09-06",
  },
  {
    id: "t8",
    title: "Tol & Parkir",
    amount: 400_000,
    type: "expense",
    category: "Transport",
    date: "2026-09-09",
  },
  {
    id: "t9",
    title: "Token Listrik PLN",
    amount: 850_000,
    type: "expense",
    category: "Bills",
    date: "2026-09-04",
  },
  {
    id: "t10",
    title: "Internet & Telepon IndiHome",
    amount: 650_000,
    type: "expense",
    category: "Bills",
    date: "2026-09-04",
  },
  {
    id: "t11",
    title: "Air PDAM",
    amount: 300_000,
    type: "expense",
    category: "Bills",
    date: "2026-09-05",
  },
  {
    id: "t12",
    title: "Pulsa Keluarga",
    amount: 300_000,
    type: "expense",
    category: "Bills",
    date: "2026-09-07",
  },
  {
    id: "t13",
    title: "Kontrol Kehamilan - RS Ibu & Anak",
    amount: 1_200_000,
    type: "expense",
    category: "Health",
    date: "2026-09-10",
    description: "USG trimester kedua",
  },
  {
    id: "t14",
    title: "Vitamin Kehamilan & Susu Hamil",
    amount: 350_000,
    type: "expense",
    category: "Health",
    date: "2026-09-06",
  },
  {
    id: "t15",
    title: "Vaksin & Vitamin Anak",
    amount: 250_000,
    type: "expense",
    category: "Health",
    date: "2026-09-07",
  },
  {
    id: "t16",
    title: "SPP TK Tunas Bangsa",
    amount: 1_200_000,
    type: "expense",
    category: "Education",
    date: "2026-09-01",
  },
  {
    id: "t17",
    title: "Buku & Perlengkapan Sekolah",
    amount: 300_000,
    type: "expense",
    category: "Education",
    date: "2026-09-03",
  },
  {
    id: "t18",
    title: "Popok & Perlengkapan Bayi",
    amount: 850_000,
    type: "expense",
    category: "Shopping",
    date: "2026-09-09",
  },
  {
    id: "t19",
    title: "Baju Anak & Kebutuhan Rumah",
    amount: 500_000,
    type: "expense",
    category: "Shopping",
    date: "2026-09-05",
  },
  {
    id: "t20",
    title: "Perlengkapan Menyambut Adik Bayi",
    amount: 300_000,
    type: "expense",
    category: "Shopping",
    date: "2026-09-11",
  },
  {
    id: "t21",
    title: "Nonton Bioskop Keluarga",
    amount: 300_000,
    type: "expense",
    category: "Entertainment",
    date: "2026-09-08",
  },
  {
    id: "t22",
    title: "Wisata Akhir Pekan",
    amount: 300_000,
    type: "expense",
    category: "Entertainment",
    date: "2026-09-12",
  },
  {
    id: "t23",
    title: "Donasi & Lainnya",
    amount: 400_000,
    type: "expense",
    category: "Other",
    date: "2026-09-02",
  },
];
